*------------------------------------------------------------*;
* TRANSFORM: HOUSE_VAL , log(HOUSE_VAL + 1);
*------------------------------------------------------------*;
label LOG_HOUSE_VAL = 'Transformed: Housing value';
if HOUSE_VAL eq . then LOG_HOUSE_VAL = .;
else do;
if HOUSE_VAL + 1 > 0 then LOG_HOUSE_VAL = log(HOUSE_VAL + 1);
else LOG_HOUSE_VAL = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: INCOME , log(INCOME + 1);
*------------------------------------------------------------*;
label LOG_INCOME = 'Transformed: Income';
if INCOME eq . then LOG_INCOME = .;
else do;
if INCOME + 1 > 0 then LOG_INCOME = log(INCOME + 1);
else LOG_INCOME = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: VEHICLE_VAL , log(VEHICLE_VAL + 1);
*------------------------------------------------------------*;
label LOG_VEHICLE_VAL = 'Transformed: Vehicle value';
if VEHICLE_VAL eq . then LOG_VEHICLE_VAL = .;
else do;
if VEHICLE_VAL + 1 > 0 then LOG_VEHICLE_VAL = log(VEHICLE_VAL + 1);
else LOG_VEHICLE_VAL = .;
end;
