*;
*MOST FREQUENT VALUE (COUNT);
*;
length IMP_JOB $13;
format IMP_JOB $13.;
label IMP_JOB = 'Imputed: Occupation of driver';
IMP_JOB = JOB;
if JOB = '' then IMP_JOB = 'Teacher';
*;
*MEAN-MAX-MIN-MEDIAN-MIDRANGE AND ROBUST ESTIMATES;
*;
format IMP_AGE 4.0;
label IMP_AGE = 'Imputed: Age';
IMP_AGE = AGE;
if missing(AGE) then IMP_AGE = 53.745808019;
label IMP_LOG_HOUSE_VAL = 'Imputed: Transformed: Housing value';
IMP_LOG_HOUSE_VAL = LOG_HOUSE_VAL;
if missing(LOG_HOUSE_VAL) then IMP_LOG_HOUSE_VAL = 12.68340528;
label IMP_LOG_INCOME = 'Imputed: Transformed: Income';
IMP_LOG_INCOME = LOG_INCOME;
if missing(LOG_INCOME) then IMP_LOG_INCOME = 10.5053851;
format IMP_VEHICLE_AGE 4.0;
label IMP_VEHICLE_AGE = 'Imputed: Age of Vehicle';
IMP_VEHICLE_AGE = VEHICLE_AGE;
if missing(VEHICLE_AGE) then IMP_VEHICLE_AGE = 10.19524179;
format IMP_YOJ 4.0;
label IMP_YOJ = 'Imputed: Years on Job';
IMP_YOJ = YOJ;
if missing(YOJ) then IMP_YOJ = 13.45563488;
*;
*INDICATOR VARIABLES;
*;
label M_AGE = "Imputation Indicator for AGE";
if missing(AGE) then M_AGE = 1;
else M_AGE= 0;
label M_JOB = "Imputation Indicator for JOB";
if JOB = '' then M_JOB = 1;
else M_JOB= 0;
label M_LOG_HOUSE_VAL = "Imputation Indicator for LOG_HOUSE_VAL";
if missing(LOG_HOUSE_VAL) then M_LOG_HOUSE_VAL = 1;
else M_LOG_HOUSE_VAL= 0;
label M_LOG_INCOME = "Imputation Indicator for LOG_INCOME";
if missing(LOG_INCOME) then M_LOG_INCOME = 1;
else M_LOG_INCOME= 0;
label M_VEHICLE_AGE = "Imputation Indicator for VEHICLE_AGE";
if missing(VEHICLE_AGE) then M_VEHICLE_AGE = 1;
else M_VEHICLE_AGE= 0;
label M_YOJ = "Imputation Indicator for YOJ";
if missing(YOJ) then M_YOJ = 1;
else M_YOJ= 0;
